server:
  httplisten:  "0.0.0.0:80"

log:
  encoding:       "json"
  outputpaths:
    - "log/app.log"
    - "stdout"
  level:          "debug"
  initialfields:
    app:          "app"

db:
  reference:
    dialect:        "postgres"
    dsn:            "host=db port=5432 dbname=reference user=postgres password=1gjcnuhtc1! sslmode=disable"
    isautomigrate:  True
    log:
      loglevel:     4
  datasharding:
    isautomigrate:  True
    default:
      capacity:  1000000
      items:
        - dialect:        "postgres"
          dsn:            "host=db port=5432 dbname=data user=postgres password=1gjcnuhtc1! sslmode=disable"
          log:
            loglevel:     4

    BySysnames:
      AdvertisingCampaigns:
        capacity:  100000000
        entitytypes:
          - AdvertisingCampaign
          - Offer
        items:
          - dialect:        "postgres"
            dsn:            "host=db port=5432 dbname=data_rotated user=postgres password=1gjcnuhtc1! sslmode=disable"
            log:
              loglevel:     4

  redis:
    addrs:
      - "redis:6379"
    login:    ""
    password: ""
    dbname:   0

auth:
  endpoint:     "http://identity:8000"
  clientId:     "ec40429a043eb4952b08"
  clientSecret: "3dc4e6160778584ddd94049e08f0a0ae8bd80cdb"
  organization: "socbazar"
  application:  "socbazar"
  SignInRedirectURL:  "http://localhost/api/account/signin"
  jwtsigningkey: "LxsKJywDL5O5PvgODZhBH12KE6k2yL8E"
  jwtexpiration: 72
  sessionlifetime: 96
  DefaultAccountSettings:
    Lang: "rus"

CacheLifeTime:  240


Socnets:

  Telegram:
    Application:
      Title:            "Yaruzz"
      ShortName:        "yaruzz"
      AppID:            16433962
      AppHash:          "c47038063d593134511bb756011fb409"
      ServerHost:       "149.154.167.40:443"
      PublicKeyFile:    "config/tg_public_keys.pem"
      InitWarnChannel:  True

